name: Android Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build-android.yml
    secrets: inherit
    with:
      upload-artifact: true
