name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
env:
  VERSION: "1.4.0"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: RustDesk.RustDesk
          version: ${{ env.VERSION }}
          token: ${{ secrets.WINGET_TOKEN }}
